web_project/gallerino/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = "gallerino"
urlpatterns = [
    # path("", views.index, name="index")
    path('', display_galleries, name = 'display_galleries'),
    path('create', create_gallery, name = 'create_gallery' ),
    # path('gallery', display_images, name = 'display_images'),
    path('gallery/<int:gallery_id>/', display_images, name = 'display_images'),
    path('image_upload/<int:gallery_id>/', image_upload, name = 'image_upload'),
    path('gallery_success/<int:gallery_id>', gallery_success, name = 'gallery_success'),
    path('success/<int:gallery_id>', success, name = 'success'),
    path('delete/<int:image_id>/', delete_image, name='delete_image'),

]

web_project/web_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from account.views import SignUpView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gallerino/', include('gallerino.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_project/gallerino/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Gallery (models.Model):

    title = models.CharField(max_length=60, default='My Gallery')
    description = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    thumbnail = models.ImageField(upload_to='images/', default='gallerino_thumbnail_placeholder.png')
    pub_date = models.DateTimeField('Date published', auto_now_add=True)
    mod_date = models.DateTimeField('Date modified', auto_now=True)
    placeholder = models.BooleanField(default=True)
    


class Post(models.Model):

    image = models.ImageField(upload_to='images/')
    description = models.CharField(max_length=200)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, default=1)       #Tän vois muuttaa ettei saa olla null mut nyt on myöhä ja aivot sulaa
    pub_date = models.DateTimeField('Date published', auto_now_add=True)
    mod_date = models.DateTimeField('Date modified', auto_now=True)


web_project/gallerino/forms.py
from django import forms
from .models import Post, Gallery



class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = {'title' ,'description', 'thumbnail'}

    def __init__(self, *args, **kwargs):
        super(GalleryForm, self).__init__(*args, **kwargs)
        self.fields['thumbnail'].required = False

class UploadForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['description', 'image']

web_project/gallerino/views.py

from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Gallery
from .forms import UploadForm, GalleryForm
# from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from PIL import Image, ImageSequence
from django.conf import settings
from django.core.files.base import ContentFile
import os
from io import BytesIO




@login_required
def display_galleries(request):
    if request.method == "GET":
        galleries = Gallery.objects.filter(user = request.user)
        return render(request, 'gallerino/index.html', {'galleries': galleries})


@login_required
def display_images(request, gallery_id):
    if request.method == "GET":
        gallery = get_object_or_404(Gallery, pk=gallery_id)
        posts = Post.objects.filter(gallery = gallery)
        return render(request, 'gallerino/gallery.html', {'posts': posts, 'gallery': gallery})



# from PIL import Image, ImageSequence

def resize_image(image_file, size=(500, 500), quality=95):
    with Image.open(image_file) as image:
        if image.format == 'PNG':
            rgba_image = image.convert('RGBA')
            background = Image.new('RGBA', rgba_image.size, (255, 255, 255))
            resized_image = Image.alpha_composite(background, rgba_image)
            resized_image = resized_image.resize(size)
            resized_image = resized_image.convert('RGB')
        elif image.format == 'GIF':
            frames = []
            for frame in ImageSequence.Iterator(image):
                resized_frame = frame.resize(size)
                resized_frame = resized_frame.convert('RGB')  # Convert GIF frames to RGB
                frames.append(resized_frame)
            resized_image = frames[0] if len(frames) == 1 else frames
        else:
            resized_image = image.resize(size)
            if resized_image.mode != 'RGB':
                resized_image = resized_image.convert('RGB')

        resized_image_io = BytesIO()
        if image.format == 'GIF':
            resized_image[0].save(resized_image_io, format='GIF', save_all=True, append_images=resized_image[1:], quality=quality)
        elif image.format == 'PNG':
            resized_image.save(resized_image_io, format='PNG', optimize=True, quality=quality)
        else:
            resized_image.save(resized_image_io, format='JPEG', quality=quality)

        resized_image_io.seek(0)
        resized_image_content = ContentFile(resized_image_io.getvalue())
        resized_image_content.name = image_file.name
        return resized_image_content




@login_required
def create_gallery(request):
    if request.method == 'POST':
        form = GalleryForm(request.POST, request.FILES)
        if form.is_valid():
            gallery = form.save(commit = False)
            gallery.user = request.user
            if 'thumbnail' in request.FILES:
                thumbnail_file = request.FILES['thumbnail']
                resized_thumbnail = resize_image(thumbnail_file, size=(500, 500), quality=100)
                gallery.thumbnail = resized_thumbnail
            else:
                # Set default thumbnail
                default_thumbnail_path = os.path.join(settings.MEDIA_ROOT, 'gallerino_thumbnail_placeholder.png')
                with open(default_thumbnail_path, 'rb') as f:
                    default_thumbnail_content = f.read()
                default_thumbnail = ContentFile(default_thumbnail_content)
                gallery.thumbnail.save('default_thumbnail.jpg', default_thumbnail)
            gallery.save()
            return redirect('gallerino:gallery_success', gallery_id=gallery.pk)
    else:
        form = GalleryForm()
    return render(request, 'gallerino/gallery_creation.html', {'form': form})




@login_required
def image_upload(request, gallery_id):
    gallery = get_object_or_404(Gallery, pk=gallery_id)
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.gallery = gallery
            if 'image' in request.FILES:
                image_file = request.FILES['image']
                resized_image = resize_image(image_file)
                post.image = resized_image
            post.save()
            if gallery.placeholder and gallery.post_set.exists():

                first_image = gallery.post_set.order_by('id').first()
                if first_image:
                    gallery.thumbnail = first_image.image
                    gallery.save()
            return redirect(reverse('gallerino:success', kwargs={'gallery_id' : gallery_id}))
    else:
        form = UploadForm()
    return render(request, 'gallerino/upload.html', {'form': form, 'gallery': gallery})




@login_required
def gallery_success(request, gallery_id):
    gallery = get_object_or_404(Gallery, pk=gallery_id)
    return render(request, 'gallerino/gallery_success.html', {'gallery': gallery})



@login_required
def success(request, gallery_id):
    gallery = get_object_or_404(Gallery, pk=gallery_id)
    return render(request, 'gallerino/success.html', {'gallery': gallery})
   
   



@login_required
def delete_image(request, image_id):
    if request.method == 'POST':
        image = get_object_or_404(Post, pk=image_id)
        gallery_id = image.gallery.pk
        image.delete()
        return redirect('gallerino:display_images', gallery_id=gallery_id)



web_project/gallerino/templates/gallerino/gallery.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>gallerino</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
        </script>
        <style>
                body{
                    text-align: center;
                    background-color: #f5f6f8;
                }
                .col-md-12 {
                    padding: 30px;
                    margin: auto;
                    margin-top: 40px;
                    background-color: white;
                }
        </style>
    </head>
    <body>
        <div class="col-md-12">
            <h1>Gallerino</h1>
            <h2>{{gallery.title}}</h2>
            <p><a href="{% url 'gallerino:image_upload' gallery_id=gallery.id %}">Upload more images</a></p>
            <p><a href="{% url 'gallerino:display_galleries' %}">Go to main page</a></p>
        </div>
        <div id="row">
            {% for post in posts %}
            <div class="col-md-4">
                <p>{{ post.description }}</p>
                <img src="{{ post.image.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" />
                <form method="post" action="{% url 'gallerino:delete_image' image_id=post.id %}">
                    {% csrf_token %}
                    <button type="submit">Delete Image</button>
                </form>
            </div>    
            {% endfor %}
        </div>
    </body>
</html>

web_project/gallerino/templates/gallerino/gallery_creation.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Gallerino - Create</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <style>
            body{
                text-align:center;
                background-color: #f5f6f8;
            }
            #view {
                padding: 30px;
                margin: auto;
                margin-top: 40px;
                max-width: 50%;
                background-color: white;
            }

        </style>
    </head>
    <body>
        <div id="view">
            <h1>Gallery Creation</h1>
            <form method = "post" enctype="multipart/form-data">
                {% csrf_token %}
                
                {{ form.as_p }}
                
                <button type="submit">Create</button>
            </form>
            <p><a href="{% url 'gallerino:display_galleries' %}">Go back to main page</a></p>
        </div>        
    </body>
</html>

web_project/gallerino/templates/gallerino/gallery_success.html
<head>
    <meta charset="UTF-8">
    <title>Gallerino - Create</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
        body{
            text-align:center;
            background-color: #f5f6f8;
        }
        #view {
            margin: 0 auto;
            margin-top: 70px;
            max-width: 50%;
            background-color: white;
            font-size: 20px;
            padding-top: 30px;
            padding-bottom: 30px;
        }
    </style>
</head>
<body>
    <div id="view"> 
        <p>Gallery created! What would you like to do next?</p>
        <p><a href="{% url 'gallerino:image_upload' gallery_id=gallery.id %}">Add images to gallery</a></p>
        <p><a href="{% url 'gallerino:display_galleries' %}">Go back to main page</a></p>
    </div>
</body>

web_project/gallerino/templates/gallerino/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Gallerino</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>

    {% block stylesheet %}
    <style>
        body{
            text-align: center;
            background-color: #f5f6f8;
        }
        .col-md-12{
            background-color:white;
        }
    </style>
    {% endblock %}

    <body>
        <div class="col-md-12">
            <h1>Gallerino</h1>
            <p><a href="{% url 'gallerino:create_gallery' %}">Create a gallery for your photos</a></p>
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
            </form>
        </div>
        {% for gallery in galleries %}
        <div class="col-md-4">
            <a href="{% url 'gallerino:display_images' gallery_id=gallery.id %}">
            <h3>{{ gallery.title }}</h3>
            <img src="{{ gallery.thumbnail.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" />
            </a>
        </div>
        {% endfor %}

    </body>
</html>

web_project/gallerino/templates/gallerino/success.html
<head>
  <meta charset="UTF-8" />
  <title>Gallerino - Create</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
  />
  <style>
    body {
      text-align: center;
      background-color: #f5f6f8;
    }
    #view {
      margin: 0 auto;
      margin-top: 70px;
      max-width: 50%;
      background-color: white;
      padding-top: 30px;
      padding-bottom: 30px;
    }
  </style>
</head>
<div id="view">
  <h3>Image has been uploaded. What would you like to do next?</h3>
  <p>
    <a href="{% url 'gallerino:image_upload' gallery_id=gallery.id%}"
      >Upload more images</a
    >
  </p>
  <p>
    <a href="{% url 'gallerino:display_images' gallery_id=gallery.id %}"
      >Go to the gallery you added a new image to</a
    >
  </p>
  <p>
    <a href="{% url 'gallerino:display_galleries' %}">Go back to main page</a>
  </p>
</div>

web_project/gallerino/templates/gallerino/upload.html
<head>
    <meta charset="UTF-8">
    <title>Gallerino - Create</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
        body{
            text-align:center;
            background-color: #f5f6f8;
        }
        #view {
            margin: 0 auto;
            margin-top: 70px;
            max-width: 50%;
            background-color: white;
            padding-top: 30px;
            padding-bottom: 30px;
        }

    </style>
</head>
<body>
    <div id="view">
        <h1>Image Upload</h1>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
                <button type="submit">Upload</button>
        </form>

        <p><a href="{% url 'gallerino:display_images' gallery_id=gallery.id %}">Go back to main page</a></p>
    </div>
</body>